module.exports = {
  urls: {
    loginPage: 'http://localhost:8000/accounts/signin/',
    dashboardPage: 'http://localhost:8000/calendar/calendar/view/',
    catalogExamination: 'http://localhost:8000/catalogs/examinations/',
    CreateStockPage: 'http://localhost:8000/stocks/items/create/',
    CreateMedicine:'http://localhost:8000/medicine/add/',
    EventPage: 'http://localhost:8000/calendar/event/list/',
    ExaminationPage: 'http://localhost:8000/examination/list/',
    CreateExaminationPage: 'http://localhost:8000/catalogs/examinations/create/',
    PatientPage: 'http://localhost:8000/customer/list/',
    Treatments: 'http://localhost:8000/treatment/list/',
    Medicine: 'http://localhost:8000/medicine/list/',
    Doctors: 'http://localhost:8000/doctor/list/',
    DebtsPage: 'http://localhost:8000/debt/',
    StockPage: 'http://localhost:8000/stocks/items/',
    StockMovementPage: 'http://localhost:8000/stocks/movements/',
    CreateStockMovement: 'http://localhost:8000/stocks/movements/create/',
    CreateStockSuplier: 'http://localhost:8000/stocks/suppliers/create/',
    CreateDoctor: 'http://localhost:8000/doctors/add/',
    DoctorsPage: 'http://localhost:8000/doctors/list/',
    StockSupliers: 'http://localhost:8000/stocks/suppliers/',
    Settings: 'http://localhost:8000/settings/',
    PersonalInfo: 'http://localhost:8000/accounts/me/view/',
    EditPersonalInfo: 'http://localhost:8000/accounts/me/edit/',
    Logout: 'http://localhost:8000/accounts/logout/',
    AddEvent: 'http://localhost:8000/calendar/event/create/',
    AddPatient: 'http://localhost:8000/customer/add/',
    AddTreatment: 'http://localhost:8000/treatment/create/',
    Payments: 'http://localhost:8000/payments/list/',
    AddMedicine: 'http://localhost:8000/medicine/add/',
    AddDoctor: 'http://localhost:8000/doctor/add/',
    AddDebts: 'http://localhost:8000/debt/add/',
    AddStock: 'http://localhost:8000/stock/add/',
    AddSettings: 'http://localhost:8000/settings/add/',
    AddUser: 'http://localhost:8000/user/add/',
    AddRole: 'http://localhost:8000/role/add/',
    User: 'http://localhost:8000/user/list/',
    Role: 'http://localhost:8000/role/list/',
    AddPayment: 'http://localhost:8000/payments/add/',
    AddStockCategory: 'http://localhost:8000/stock/category/add/',
    AddStockLocation: 'http://localhost:8000/stock/location/add/',
    StockCategory: 'http://localhost:8000/stock/category/list/',
    StockLocation: 'http://localhost:8000/stock/location/list/',
    StockTransaction: 'http://localhost:8000/stock/transaction/list/',
    AddStockTransaction: 'http://localhost:8000/stock/transaction/add/',
    StockTransactionType: 'http://localhost:8000/stock/transaction/type/list/',
    TransactionsPage:'http://localhost:8000/debit/list/',
    CreateTransactions:'http://localhost:8000/debit/add/',
    PackagePage:'http://localhost:8000/package/',
    CreatePackage:'http://localhost:8000/package/create/',
    PatientPackagePage:'http://localhost:8000/package/patient-packages/',
    CreatePatientPackage:'http://localhost:8000/package/patient-packages/create/',
    TransactionCategoryPage:'http://localhost:8000/tcategories/list/',
    CreateTransactionCategory:'http://localhost:8000/tcategories/add/',
    RoomsPage:'http://localhost:8000/calendar/room/list/',
    CreateRoom:'http://localhost:8000/calendar/room/create/',
    CatalogCourse:'http://localhost:8000/catalogs/courses/',
    CreateCatalogCourses:'http://localhost:8000/catalogs/courses/create/',
    CreateCatalogTreatments:'http://localhost:8000/catalogs/treatments/create/',
    CatalogTreatment:'http://localhost:8000/catalogs/treatments/',





  },
  credentials: {
    email: 'veysellbalck@gmail.com',
    password: 'S7jr79wrE7'
  }
};